# File: .github/workflows/repo-sync.yml
name: sync-lxk0301-scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lxk0301-scripts
jobs:
  repo-sync:
    env:
      #PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lxk0301-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
          black_list: 'repo_sync'
          
      - name: sync gitee -> github
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: gitee/lxk0301
          dst: github/smiek
          static_list: "jd_scripts"
          dst_key: ${{ secrets.PRIVATE_KEY }}
          dst_token: ${{ secrets.PAT }}
